version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Build
          command: npm run build

      - run:
          name: Scrape
          command: npm run scrape

      - run:
          name: Copy data to build folder
          command: npm run copydata

      - run:
          name: Deploy on Zeit now
          command: npx now -t ${NOW_TOKEN} ./build -A ../now.json

      - run:
          name: Alias domain chockpress.now.sh
          command: npx now -t ${NOW_TOKEN} alias chockpress

      - run:
          name: Save data to Google Sheet
          command: npm run save

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  daily-workflow:
    triggers:
      - schedule:
          cron: '0 14 * * *'
          filters:
            branches:
              only:
                - dev
    jobs:
      - build
