version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Build
          command: npm run build

      - run:
          name: Scrape
          command: npm run scrape

      - run:
          name: Copy data to build folder
          command: cp -R ./src/data/ build/data

      - run:
          name: Deploy on Zeit now
          command: npx now -t ${NOW_TOKEN} ./build -A ../now.json

      - run:
          name: Alias domain chockpress.now.sh
          command: npx now -t ${NOW_TOKEN} alias chockpress

      - run:
          name: Save data to database
          command: npm run save

      - run:
          name: Store database file as artifact
          command: |
            mkdir ~/repo/db/;
            cp ./src/scraper/helpers/db.json ~/repo/db

      - store_artifacts:
          path: ~/repo/db
          destination: db-file

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  daily-workflow:
    triggers:
      - schedule:
          cron: '0 * * * *'
          filters:
            branches:
              only:
                - dev
    jobs:
      - build
