version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          - dependency-cache-

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run: npm run clean

      - run: npm run build

      - run: npm run scrape

      - run: cp -R ./src/data/ build/data

      - run: now -t ${NOW_TOKEN}

      - run: now -t ${NOW_TOKEN} alias chockpress

      - run: npm run save


workflows:
  version: 2

  # nightly:
  #   triggers:
  #     - schedule:
  #         # UTC 5:00 AM = EST 12:00 AM daily
  #         cron: "0 5 * * *"
  #         filters:
  #           branches:
  #             only:
  #               - master
    jobs:
      - build
